custom:
  accent: "#00626e"

plugins:
  - jekyll-paginate
  - jemoji
permalink: pretty

title: Ask
url: https://david.quotient.space
baseurl: /ask
success_path: /success
paginate: 20

author:
  name: 'David'
  twitter: fdavidcl

avatar: "https://secure.gravatar.com/avatar/7083d161b041964b75c38376d9dee37a?s=200"


# localization
lang: en