# The title of your site
title: nosykitty

author:
  name: nosykitty
# uncomment to customize your avatar:
#  avatar: "http://david.quotient.space/nosykitty/assets/kitty.svg"

# Put here the url to your site (e.g. url: https://username.github.io and baseurl: /ask)
url: http://david.quotient.space
baseurl: /nosykitty

# Customization
custom:
  accent: "blue"
  prompt: "Ask a question! It will be public on Github before it is answered"
  followup_prompt: "Answer with another question?"
  

# Localization
lang: en

# Configuration stuff you don't care about
plugins:
  - jekyll-paginate
  - jemoji
permalink: pretty
success_path: /success
paginate: 20